version: '3.9'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
    depends_on:
      - mysql_db
    networks:
      - app-tier

  mysql_db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: production
      MYSQL_USER: aquarium
      MYSQL_PASSWORD: aSecretAquarium
      MYSQL_ROOT_PASSWORD: aSecretAquarium
    volumes:
      - ./data/db:/var/lib/mysql
      - ./data/mysql_init/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
